apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotnetworld
spec:
  replicas: 1 
  template: 
    metadata:
      labels:
        app: Hello-world
    spec:
      containers:
      - name: dotnetworld
        image: microdepp.azurecr.io/hello-world:BuildId
        ports:
        - containerPort: 80
