apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotnetworld
spec:
  replicas: 1 
  template: 
    metadata:
      labels:
        app: Hello-world
    spec:
      containers:
      - name: dotnetworld
        image: microdepp.azurecr.io/hello-world:$(Build.BuildId)
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetworld
spec:
  selector: 
    app: Hello-world
  type: LoadBalancer
  ports:
    - name: my-port
      port: 8080
      targetPort: 80
